tasks:
  - init: yarn
    command: 'echo "TODO: Replace with command to start project"'

ports:
  - port: 8000
    onOpen: open-preview
vscode:
  extensions:
    - elmTooling.elm-ls-vscode@1.1.1:V7e0myIRioA+vC8/uv+Cmw==